// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8GKuFnbxhWyk2DtvAzC_5laBDUSreKMk',
    appId: '1:367439252526:web:6774f9cddf1c0f1570a3bf',
    messagingSenderId: '367439252526',
    projectId: 'myperiodtracker-eb0fa',
    authDomain: 'myperiodtracker-eb0fa.firebaseapp.com',
    storageBucket: 'myperiodtracker-eb0fa.firebasestorage.app',
    measurementId: 'G-2MWNE9Y7N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_xEUwP-mvEUwaGMZR_mQrG6xYhZbfvh0',
    appId: '1:367439252526:android:5afef3de838137af70a3bf',
    messagingSenderId: '367439252526',
    projectId: 'myperiodtracker-eb0fa',
    storageBucket: 'myperiodtracker-eb0fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUP45Q9ukB6uPALYiHZmdbzzjkrrYooJM',
    appId: '1:367439252526:ios:65a0b8b43a99ee4470a3bf',
    messagingSenderId: '367439252526',
    projectId: 'myperiodtracker-eb0fa',
    storageBucket: 'myperiodtracker-eb0fa.firebasestorage.app',
    iosBundleId: 'com.periodtracker1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUP45Q9ukB6uPALYiHZmdbzzjkrrYooJM',
    appId: '1:367439252526:ios:44703ff86e2993c670a3bf',
    messagingSenderId: '367439252526',
    projectId: 'myperiodtracker-eb0fa',
    storageBucket: 'myperiodtracker-eb0fa.firebasestorage.app',
    iosBundleId: 'com.example.periodtracker1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8GKuFnbxhWyk2DtvAzC_5laBDUSreKMk',
    appId: '1:367439252526:web:6774f9cddf1c0f1570a3bf',
    messagingSenderId: '367439252526',
    projectId: 'myperiodtracker-eb0fa',
    authDomain: 'myperiodtracker-eb0fa.firebaseapp.com',
    storageBucket: 'myperiodtracker-eb0fa.firebasestorage.app',
    measurementId: 'G-2MWNE9Y7N4',
  );
}
